### PR TITLE
Fix tid key; simplify tid generation

### PR DESCRIPTION
**Pull request by gotha**
# Description

## What

TransactionIDKey should not be string, fixed it

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [x] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

### CODE REVIEW

**Review by MiroslavGatsanoga — COMMENTED** [review]
A couple of questions:
- I am not sure what are actually fixing, can we have a unit test that demonstrates the bug?
- What justifies the change of the transaction id generation code? My personal opinion is that even if the code might look like more readable introducing a new dependency could make things more complicated e.g. `uniuri` could panic.
- We completely changing the underlying implementation (old one is based on `math/rand`, new one is based on `crypto/rand`), which could be seen as a breaking change, so perhaps we should consider releasing two major versions of the module?

**Comment by gotha** [comment]
@MiroslavGatsanoga the change from math/rand to crypto/rand was suggested by the linters. 
If we want to make our own implementation (and we follow the suggestion to use crypto/rand) we will end up with similar code without the benefits of using third party library. 

I still think that it is better to rely on third party lib for generating random strings as it is more likely that they have thought of more corner cases than me.

**Comment by MiroslavGatsanoga** [comment]
@gotha Ok, so as far I understand the actual purpose of the PR is not about something specific as using cryptographic RNG, simplifying tid generation or making TransactionIDKey to not be a string, but it is just about fixing linter warnings.
Here are my suggestions:
 - The linter warning `should not use basic type string as key in context.WithValue` is not about strings, it's about basic types e.g. `const TransactionIDKey int = 0` would produce the same warning but for `int`. I see that you have defined an unexported type as it is recommended, but [it is also recommended](https://github.com/golang/net/blob/master/context/pre_go19.go#L91) to make `TransactionIDKey` unexported as well.
 - Let's update the docstring of `GetTransactionIDFromRequest` to say that there could be a side effect of modifying the passed request.

About the third party dependency: I am not too keen on introducing it just to make `gosec` happy, but if the team thinks we are better off with using `crypto/rand` I am be fine with it.

**Comment by gotha** [comment]
thanks @MiroslavGatsanoga 
I gave "string" as an example, of course int will be the same. 

I did not change `TransactionIDKey` for compatibility reasons. 
https://github.com/Financial-Times/go-ft-http/blob/master/transport/extensions.go
Now we will have to fix this and possibly other libraries.

I also find it weird that `GetTransactionIDFromRequest` modifies the request, but it is old code and I did not want to change it for the same reasons.

**Review by MiroslavGatsanoga — APPROVED** [review]

**Review by StephanZahariev — APPROVED** [review]

**Pull request merged**
